export interface UserInfo {
  user_id: string
  userName: string
  avatar: string
}

export const DefaultUserList: UserInfo[] = [
  {
    user_id: '1',
    userName: '小趴菜',
    avatar: 'https://p5.ssl.qhimgs1.com/sdr/400__/t01afd659fd808105bf.jpg'
  },
  {
    user_id: '2',
    userName: '吊毛',
    avatar: 'https://p0.ssl.qhimgs1.com/sdr/400__/t04a531e3bc571a734a.jpg'
  }, {
  user_id: '3',
  userName: '小鬼子',
  avatar: 'https://p0.ssl.qhimgs1.com/sdr/400__/t04d1799d23d747bfa4.jpg'
}, {
  user_id: '4',
  userName: '新鲜玩意儿',
  avatar: 'https://p2.ssl.qhimgs1.com/sdr/400__/t048d5f158b6a714f72.jpg'
}, {
  user_id: '5',
  userName: '亮姐',
  avatar: 'https://p1.ssl.qhimgs1.com/sdr/400__/t016efb6d1cdc9027fb.jpg'
}, {
  user_id: '6',
  userName: '猜猜',
  avatar: 'https://p1.ssl.qhimgs1.com/sdr/400__/t017e89e20cf4063afb.jpg'
}, {
  user_id: '7',
  userName: '月亮',
  avatar: 'https://p0.ssl.qhimgs1.com/sdr/400__/t01610ff42b2716ea56.jpg'
}, {
  user_id: '8',
  userName: '火火恍恍惚惚',
  avatar: 'https://p0.ssl.qhimgs1.com/sdr/400__/t04d4e91a735c7175aa.jpg'
}, {
  user_id: '9',
  userName: '嘿嘿嘿嘿嘿嘿',
  avatar: 'https://p0.ssl.qhimgs1.com/sdr/400__/t014b9a4bce34d49456.jpg'
}, {
  user_id: '10',
  userName: '星光大道',
  avatar: 'https://p0.ssl.qhimgs1.com/sdr/400__/t010994bfd954cb27f6.jpg'
}, {
  user_id: '11',
  userName: '李逍遥',
  avatar: 'https://p2.ssl.qhimgs1.com/sdr/400__/t012f6fe0967493a4a2.jpg'
}, {
  user_id: '12',
  userName: '邪剑仙',
  avatar: 'https://p1.ssl.qhimgs1.com/sdr/400__/t04c94b479c96f25717.jpg'
}, {
  user_id: '13',
  userName: '景天',
  avatar: 'https://p1.ssl.qhimgs1.com/sdr/400__/t0408e37f9c3131e987.jpg'
}, {
  user_id: '14',
  userName: '茂茂',
  avatar: 'https://p0.ssl.qhimgs1.com/sdr/400__/t040992dd93317c4a76.jpg'
}, {
  user_id: '15',
  userName: '冬天',
  avatar: 'https://p0.ssl.qhimgs1.com/sdr/400__/t0459f471728e8c1304.jpg'
},
]